config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "orders#index"
      resources :orders do
        member do
          put :approve
          put :reject
        end
      end
      get "order_status/:status", to: "orders#index_by_status", as: :status
      resources :products, except: :delete do
        collection {post :import}
        member do
          delete :purge_images
          delete :purge_thumbnail
        end
      end
    end

    root "static_pages#home"
    get :home, to: "static_pages#home"
    get :menu, to: "products#index"
    get :about, to: "static_pages#about"
    get :blog, to: "static_pages#blog"
    get :contact, to: "static_pages#contact"
    get :order, to: "orders#new"
    get "/filter/:category_id", to: "products#filter", as: :filter

    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      delete "logout" => "devise/sessions#destroy"
    end
    resources :users, only: %i(show) do
      resources :orders, only: %i(index show) do
        put :cancel, on: :member
      end
    end
    resources :products, only: %i(index show)
    resources :orders, only: %i(new create)
    resources :carts
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

  delegate :name, to: :address, prefix: true
  delegate :name, :email, to: :user, prefix: true
  enum status: {
    open: Settings.open,
    confirmed: Settings.confirmed,
    shipping: Settings.shipping,
    completed: Settings.completed,
    cancelled: Settings.cancelled,
    disclaim: Settings.disclaim
  }
  scope :recent_orders, ->{order created_at: :desc}

  validates :name, :phone, :address, presence: true,
    length: {maximum: Settings.length.max_250}
  validates :total_price, presence: true,
    numericality:
    {
      only_integer: false,
      greater_than_or_equal_to: Settings.init_number
    }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminsController
  before_action :load_order, :load_order_details,
                except: %i(index index_by_status)
  before_action :check_quantity_product, only: :approve
  before_action :set_search

  def index
    @title = t "orders.all"
    @orders = @q.result.includes(:order_details, :user)
                .recent_orders.page(params[:page])
                .per(Settings.show_10)
  end

  def index_by_status
    @title = t "status_order.#{params[:status]}"
    load_orders params[:status]
  end

  def show
    @title = t "orders.order_detail"
  end

  # change status open to confirmed
  def approve
    ActiveRecord::Base.transaction do
      if @order.open?
        update_quantity_product
        @order.confirmed!
        send_mail
        flash[:success] = t "orders.approve_success"
      else
        flash[:danger] = t "orders.approve_failed"
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.approve_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  # chang status open to disclaim
  def reject
    ActiveRecord::Base.transaction do
      add_quantity_product if @order.confirmed?
      @order.disclaim!
      send_mail
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.reject_failed"
  else
    flash[:success] = t "orders.reject_success"
  ensure
    redirect_back(fallback_location: admin_orders_path)
  end

  # change status confirmed to completed
  def update
    if @order.confirmed?
      @order.completed!
      send_mail
    else
      flash[:danger] = t "orders.update_fail"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.update_fail"
  else
    flash[:success] = t "orders.order_changed"
  ensure
    redirect_back(fallback_location: admin_orders_path)
  end

  private

  # only load 1 order param id
  def load_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:danger] = t "orders.no_order"
    redirect_to admin_orders_path
  end

  # load order details, total price
  def load_order_details
    @order_details = @order.order_details.includes(:product)
    @total = total_order @order_details
  end

  def load_orders status
    if check_status? status
      @orders = Order.send(status)
                     .includes(:order_details, :user)
                     .recent_orders.page(params[:page])
                     .per(Settings.show_10)
      render :index
    else
      flash[:success] = t "error_path"
      redirect_to admin_orders_path
    end
  end

  def total_order order_details
    order_details.reduce(0) do |total, order|
      total + order.quantity * order.price
    end
  end

  # check param status exists in the enum model order
  def check_status? status
    Order.statuses.include?(status)
  end

  def send_mail
    UserMailer.order_status(@order, @order_details, @total).deliver_now
  end

  # update quantity products when approved order
  def update_quantity_product
    @order_details.each do |detail|
      product = detail.product
      product.quantity -= detail.quantity
      product.save!
    end
  end

  # update quantity product when reject
  def add_quantity_product
    @order_details.each do |detail|
      product = detail.product
      product.quantity += detail.quantity
      product.save!
    end
  end

  # check quantity product with quantity in order detail
  def check_quantity_product
    prd_name = ""
    @order_details.each do |detail|
      if detail.product.quantity < detail.quantity
        prd_name << detail.product_name << ", "
      end
    end
    return if prd_name.blank?

    flash[:danger] = t("orders.quantity_not_enough") << prd_name
    redirect_back(fallback_location: admin_orders_path)
  end

  def set_search
    @q = Order.ransack(params[:q])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_order, :load_order_details, only: %i(show cancel)
  authorize_resource

  def index
    @orders = current_user.all_orders
                          .page(params[:page])
                          .per(Settings.show_5)
  end

  def new
    if session[:cart].blank?
      flash[:danger] = t "cart_empty"
      redirect_to root_path
    else
      qtity = session[:cart]
      @carts = Product.find_products_cart(qtity.keys)
      @total = total_money @carts
    end
  end

  def create
    ActiveRecord::Base.transaction do
      qtity = session[:cart]
      @carts = Product.find_products_cart(qtity.keys)
      @total = total_money @carts
      save_address
      order = save_order(@add)
      save_order_details order
      order.save!
      session.delete :cart
      flash[:success] = t "orders.order_success"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.order_fail"
  ensure
    redirect_to user_orders_path(current_user)
  end

  def show; end

  def cancel
    if @order.open?
      @order.cancelled!
      send_mail
    else
      flash[:danger] = t "orders.update_fail"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.update_fail"
  else
    flash[:success] = t "orders.order_changed"
  ensure
    redirect_back(fallback_location: user_order_path)
  end

  private

  def load_order
    @order = current_user.orders.find_by(id: params[:id])
    return if @order

    flash[:danger] = t "orders.no_order"
    redirect_to root_path
  end

  def load_order_details
    @order_details = @order.order_details.includes(:product)
    @total = total_order @order_details
  end

  def total_order order_details
    order_details.reduce(0) do |total, order|
      total + order.quantity * order.price
    end
  end

  def total_money arr
    arr.reduce(0) do |sum, item|
      sum + session[:cart][item.id.to_s] * item.price
    end
  end

  def send_mail
    UserMailer.order_status(@order, @order_details, @total).deliver_now
  end

  def save_address
    if params[:address].present?
      address_arr = params[:address].split("_")
      @add = current_user.addresses.create!(
        name: address_arr[0],
        phone: address_arr[1],
        address: address_arr[2],
        user_id: current_user.id
      )
    else
      @add = Address.find_by(id: params[:address_id])
    end
  end

  def save_order add
    current_user.orders.build(
      name: add.name,
      phone: add.phone,
      address: add.address,
      total_price: @total,
      address_id: add.id
    )
  end

  def save_order_details order
    qtity = session[:cart]
    qtity.each do |product_id, quantity|
      next if product_id.nil?

      product = Product.find_by(id: product_id)
      order.order_details.build(
        quantity: quantity,
        price: product.price,
        product_id: product_id
      )
      remaining_quantity = product.quantity - quantity
      product.update!(quantity: remaining_quantity)
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= l order.created_at, format: :own %></td>
  <td><%= order.name %></td>
  <td><%= order.phone %></td>
  <td><%= order.address %></td>
  <td>
    <%= number_to_currency(order.total_price, locale: :vi) %>
  </td>
  <td>
    <h5>
      <span class="badge btn <%= t "class.#{order.status}" %>">
        <%= t "status_order.#{order.status}" %>
      </span>
    </h5>
  </td>
  <td>
    <%= link_to admin_order_path(order) do %>
      <button type="button" class="btn btn-primary btn-sm">
        <i class="fa fa-eye" aria-hidden="true"></i>
      </button>
    <% end %>
    <% if order.open? %>
      <%= link_to approve_admin_order_path(order), method: :put, data: { confirm: t("you_sure") } do %>
        <button type="button" class="btn btn-info btn-sm">
          <i class="fa fa-check" aria-hidden="true"></i>
        </button>
      <% end %>
      <%= link_to reject_admin_order_path(order), method: :put, data: { confirm: t("you_sure") } do %>
        <button type="button" class="btn btn-danger btn-sm">
          <i class="fa fa-times" aria-hidden="true"></i>
        </button>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/orders/_status.html.erb
<%= link_to t("status_order.open"), admin_status_path(status: :open), class: "btn btn-primary btn-sm" %>
<%= link_to t("status_order.confirmed"), admin_status_path(status: :confirmed), class: "btn btn-info btn-sm" %>
<%= link_to t("status_order.shipping"), admin_status_path(status: :shipping), class: "btn btn-secondary btn-sm" %>
<%= link_to t("status_order.completed"), admin_status_path(status: :completed), class: "btn btn-success btn-sm" %>
<%= link_to t("status_order.cancelled"), admin_status_path(status: :cancelled), class: "btn btn-danger btn-sm" %>

app/views/admin/orders/index.html.erb
<% provide(:title, @title) %>
<div>
  <div class="page-title">
    <div class="title_left">
      <h3><b><%= t "manager_orders" %></b></br><small><%= @title %></small></h3>
    </div></br>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= search_form_for(@q, url: admin_orders_path, method: :get) do |f| %>
          <div class="input-group">
            <%= f.search_field :name_or_phone_or_address_cont, class: "form-control" %>
            <span class="input-group-btn">
                <%= f.submit t("menu_page.search"), class: "btn btn-secondary" %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_title">
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <%= render "status" %>
        <div class="x_content">
          <% if @orders.any? %>
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th><%= t "orders.created_order" %></th>
                        <th><%= t "orders.fullname" %></th>
                        <th><%= t "orders.phone" %></th>
                        <th><%= t "orders.address" %></th>
                        <th><%= t "orders.total_price" %></th>
                        <th><%= t "orders.status" %></th>
                        <th><%= t "orders.action" %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <%= render @orders %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <%= paginate @orders %>
          <% else %>
            <h1 class="text-center cart-index-title">
              <%= t "orders.no_order" %>
            </h1>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<% provide(:title, @title) %>
<div>
  <div class="page-title">
    <div class="title_left">
      <h3><b><%= @title %></b></h3>
    </div></br>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_title">
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <% if @order %>
          <div class="x_content">
            <div class="title-info-order"><%= t "orders.order_person" %></div>
            <div class="infor_order row">
              <div class="col-md-1 infor_col">
                <p><%= t "orders.fullname" %>:</p>
                <p><%= t "orders.email" %>:</p>
              </div>
              <div class="col-md-8">
                <p><%= @order.user_name %></p>
                <p><%= @order.user_email %></p>
              </div>
            </div><br>
            <div class="title-info-order"><%= t "orders.order_infor" %></div>
            <div class="infor_order row">
              <div class="col-md-1 infor_col">
                <p><%= t "orders.fullname" %>:</p>
                <p><%= t "orders.address" %>:</p>
                <p><%= t "orders.phone" %>:</p>
                <p><%= t "orders.status" %>:</p>
                <p><%= t "orders.created_order" %>:</p>
              </div>
              <div class="col-md-8">
                <p><%= @order.name %></p>
                <p><%= @order.address %></p>
                <p><%= @order.phone %></p>
                <p>
                  <span class="badge <%= t "class.#{@order.status}" %>">
                    <%= t("status_order.#{@order.status}") %>
                  </span>
                </p>
                <p><%= l @order.created_at, format: :own %></p>
              </div>
            </div>
            <!-- change status -->
            <div>
              <!-- if status is open (pending), allow accept or reject order -->
              <% if @order.open? %>
                <b><%= t "orders.change_status_to" %></b><br>
                <!-- Button approve order -->
                <%= link_to approve_admin_order_path(@order), method: :put, data: { confirm: t("you_sure") } do %>
                  <button type="button" class="btn btn-info btn-sm">
                    <i class="fa fa-check" aria-hidden="true"></i>
                  </button>
                <% end %>
                <!-- Button reject order -->
                <%= link_to reject_admin_order_path(@order), method: :put, data: { confirm: t("you_sure") } do %>
                  <button type="button" class="btn btn-danger btn-sm">
                    <i class="fa fa-times" aria-hidden="true"></i>
                  </button>
                <% end %>
              <!-- if Status confirmed, allow change order to completed or reject-->
              <% elsif @order.confirmed? %>
                <!-- Button change status to completed -->
                <%= link_to admin_order_path(@order), method: :put, data: { confirm: t("you_sure") } do %>
                  <button type="button" class="btn btn-sm <%= t("class.completed") %>">
                    <%= t "orders.change_status_to" %>
                    <%= t "status_order.completed" %>
                  </button>
                <% end %>
                <!-- Button reject order -->
                <%= link_to reject_admin_order_path(@order), method: :put, data: { confirm: t("you_sure") } do %>
                  <button type="button" class="btn btn-danger btn-sm">
                    <i class="fa fa-times" aria-hidden="true"></i>
                  </button>
                <% end %>
              <% end %>
            </div><br>
            <!-- /change status -->
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th><%= t "orders.ordinal_number" %></th>
                        <th><%= t "orders.product_name" %></th>
                        <th><%= t "orders.quantity" %></th>
                        <th><%= t "orders.price" %></th>
                        <th><%= t "orders.total_price" %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @order_details.each_with_index do |detail, i|%>
                      <tr>
                        <td><%= i+1 %></td>
                        <td><%= detail.product_name %></td>
                        <td><%= detail.quantity %></td>
                        <td><%= number_to_currency(detail.price, locale: :vi) %></td>
                        <td><%= number_to_currency(detail.price*detail.quantity, locale: :vi) %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <hr>
            <div class="d-flex justify-content-end">
              <p class="text-right total-order">
                <b><%= t "orders.total" %></b>:
                <%= number_to_currency(@total, locale: :vi) %>
              </p>
            </div>
          </div>
        <% else %>
          <h2><%= t "orders.no_order" %></h2>
        <% end %>
      </div>
    </div>
  </div>
</div>