config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "orders#index"
      resources :orders do
        member do
          put :approve
          put :reject
        end
      end
      get "order_status/:status", to: "orders#index_by_status", as: :status
      resources :products, except: :delete do
        collection {post :import}
        member do
          delete :purge_images
          delete :purge_thumbnail
        end
      end
    end

    root "static_pages#home"
    get :home, to: "static_pages#home"
    get :menu, to: "products#index"
    get :about, to: "static_pages#about"
    get :blog, to: "static_pages#blog"
    get :contact, to: "static_pages#contact"
    get :order, to: "orders#new"
    get "/filter/:category_id", to: "products#filter", as: :filter

    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      delete "logout" => "devise/sessions#destroy"
    end
    resources :users, only: %i(show) do
      resources :orders, only: %i(index show) do
        put :cancel, on: :member
      end
    end
    resources :products, only: %i(index show)
    resources :orders, only: %i(new create)
    resources :carts
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

  delegate :name, to: :address, prefix: true
  delegate :name, :email, to: :user, prefix: true
  enum status: {
    open: Settings.open,
    confirmed: Settings.confirmed,
    shipping: Settings.shipping,
    completed: Settings.completed,
    cancelled: Settings.cancelled,
    disclaim: Settings.disclaim
  }
  scope :recent_orders, ->{order created_at: :desc}

  validates :name, :phone, :address, presence: true,
    length: {maximum: Settings.length.max_250}
  validates :total_price, presence: true,
    numericality:
    {
      only_integer: false,
      greater_than_or_equal_to: Settings.init_number
    }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminsController
  before_action :load_order, :load_order_details,
                except: %i(index index_by_status)
  before_action :check_quantity_product, only: :approve
  before_action :set_search

  def index
    @title = t "orders.all"
    @orders = @q.result.includes(:order_details, :user)
                .recent_orders.page(params[:page])
                .per(Settings.show_10)
  end

  def index_by_status
    @title = t "status_order.#{params[:status]}"
    load_orders params[:status]
  end

  def show
    @title = t "orders.order_detail"
  end

  # change status open to confirmed
  def approve
    ActiveRecord::Base.transaction do
      if @order.open?
        update_quantity_product
        @order.confirmed!
        send_mail
        flash[:success] = t "orders.approve_success"
      else
        flash[:danger] = t "orders.approve_failed"
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.approve_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  # chang status open to disclaim
  def reject
    ActiveRecord::Base.transaction do
      add_quantity_product if @order.confirmed?
      @order.disclaim!
      send_mail
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.reject_failed"
  else
    flash[:success] = t "orders.reject_success"
  ensure
    redirect_back(fallback_location: admin_orders_path)
  end

  # change status confirmed to completed
  def update
    if @order.confirmed?
      @order.completed!
      send_mail
    else
      flash[:danger] = t "orders.update_fail"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.update_fail"
  else
    flash[:success] = t "orders.order_changed"
  ensure
    redirect_back(fallback_location: admin_orders_path)
  end

  private

  # only load 1 order param id
  def load_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:danger] = t "orders.no_order"
    redirect_to admin_orders_path
  end

  # load order details, total price
  def load_order_details
    @order_details = @order.order_details.includes(:product)
    @total = total_order @order_details
  end

  def load_orders status
    if check_status? status
      @orders = Order.send(status)
                     .includes(:order_details, :user)
                     .recent_orders.page(params[:page])
                     .per(Settings.show_10)
      render :index
    else
      flash[:success] = t "error_path"
      redirect_to admin_orders_path
    end
  end

  def total_order order_details
    order_details.reduce(0) do |total, order|
      total + order.quantity * order.price
    end
  end

  # check param status exists in the enum model order
  def check_status? status
    Order.statuses.include?(status)
  end

  def send_mail
    UserMailer.order_status(@order, @order_details, @total).deliver_now
  end

  # update quantity products when approved order
  def update_quantity_product
    @order_details.each do |detail|
      product = detail.product
      product.quantity -= detail.quantity
      product.save!
    end
  end

  # update quantity product when reject
  def add_quantity_product
    @order_details.each do |detail|
      product = detail.product
      product.quantity += detail.quantity
      product.save!
    end
  end

  # check quantity product with quantity in order detail
  def check_quantity_product
    prd_name = ""
    @order_details.each do |detail|
      if detail.product.quantity < detail.quantity
        prd_name << detail.product_name << ", "
      end
    end
    return if prd_name.blank?

    flash[:danger] = t("orders.quantity_not_enough") << prd_name
    redirect_back(fallback_location: admin_orders_path)
  end

  def set_search
    @q = Order.ransack(params[:q])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_order, :load_order_details, only: %i(show cancel)
  authorize_resource

  def index
    @orders = current_user.all_orders
                          .page(params[:page])
                          .per(Settings.show_5)
  end

  def new
    if session[:cart].blank?
      flash[:danger] = t "cart_empty"
      redirect_to root_path
    else
      qtity = session[:cart]
      @carts = Product.find_products_cart(qtity.keys)
      @total = total_money @carts
    end
  end

  def create
    ActiveRecord::Base.transaction do
      qtity = session[:cart]
      @carts = Product.find_products_cart(qtity.keys)
      @total = total_money @carts
      save_address
      order = save_order(@add)
      save_order_details order
      order.save!
      session.delete :cart
      flash[:success] = t "orders.order_success"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.order_fail"
  ensure
    redirect_to user_orders_path(current_user)
  end

  def show; end

  def cancel
    if @order.open?
      @order.cancelled!
      send_mail
    else
      flash[:danger] = t "orders.update_fail"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "orders.update_fail"
  else
    flash[:success] = t "orders.order_changed"
  ensure
    redirect_back(fallback_location: user_order_path)
  end

  private

  def load_order
    @order = current_user.orders.find_by(id: params[:id])
    return if @order

    flash[:danger] = t "orders.no_order"
    redirect_to root_path
  end

  def load_order_details
    @order_details = @order.order_details.includes(:product)
    @total = total_order @order_details
  end

  def total_order order_details
    order_details.reduce(0) do |total, order|
      total + order.quantity * order.price
    end
  end

  def total_money arr
    arr.reduce(0) do |sum, item|
      sum + session[:cart][item.id.to_s] * item.price
    end
  end

  def send_mail
    UserMailer.order_status(@order, @order_details, @total).deliver_now
  end

  def save_address
    if params[:address].present?
      address_arr = params[:address].split("_")
      @add = current_user.addresses.create!(
        name: address_arr[0],
        phone: address_arr[1],
        address: address_arr[2],
        user_id: current_user.id
      )
    else
      @add = Address.find_by(id: params[:address_id])
    end
  end

  def save_order add
    current_user.orders.build(
      name: add.name,
      phone: add.phone,
      address: add.address,
      total_price: @total,
      address_id: add.id
    )
  end

  def save_order_details order
    qtity = session[:cart]
    qtity.each do |product_id, quantity|
      next if product_id.nil?

      product = Product.find_by(id: product_id)
      order.order_details.build(
        quantity: quantity,
        price: product.price,
        product_id: product_id
      )
      remaining_quantity = product.quantity - quantity
      product.update!(quantity: remaining_quantity)
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<div class="tracking-item">
  <div class="tracking-icon status-intransit"></div>
  <div class="tracking-date">
    <p class="badge btn <%= t "class.#{order.status}" %>">
      <%= t "status_order.#{order.status}" %>
    </p>
  </div>
  <div class="tracking-content">
    <span><b><%= l order.created_at, format: :own %></b></span>
    <span><b><%= t "orders.order_person" %></b> <%= order.name %></span>
    <span><b><%= t "orders.address" %>:</b> <%= order.address %></span>
    <span>
      <b><%= t "orders.total_price" %></b>:
      <%= number_to_currency(order.total_price, locale: :vi) %>
    </span>
    <span>
      <%= link_to t("orders.view_detail"), user_order_path(current_user, order) %>
    </span>
  </div>
</div>

app/views/orders/_order_detail.html.erb
<tr>
  <td>
    <!-- show image -->
    <% if check_thumb? order_detail.product_thumbnail %>
      <%= image_tag order_detail.product_thumbnail, class: "image-order" %>
    <% else %>
      <%= gravatar_for order_detail.product, size: Settings.gravatar.size_100 %>
    <% end %>
  </td>
  <td>
    <%= link_to product_path(order_detail.product) do %>
      <span><%= order_detail.product_name %></span>
    <% end %>
  </td>
  <td><%= order_detail.quantity %></td>
  <td><%= number_to_currency(order_detail.price, locale: :vi) %></td>
  <td>
    <%= number_to_currency(order_detail.price*order_detail.quantity, locale: :vi) %>
  </td>
</tr>

app/views/orders/_order_form.html.erb
<%= form_tag orders_path, method: :post do %>
  <div class="form-group">
    <div class="row title-order">
      <h2 class="button-center title-order"><%= t "orders.order_information" %></h2>
    </div>
    <% current_user.addresses.each do |add| %>
      <div class="form-check field-add">
        <div class="div-left">
          <% if add.is_default? %>
            <%= radio_button_tag :address_id, add.id, true, id: "checked" %>
          <% else %>
            <%= radio_button_tag :address_id, add.id %>
          <% end %>
        </div>
        <div class="div-left">
          <%= label_tag nil, add.name, class: "form-lable" %><br>
          <%= label_tag nil, add.phone, class: "form-lable" %><br>
          <%= label_tag nil, add.address, class: "form-lable" %><br>
        </div>
      </div>
      <hr>
    <% end %>
    <div id="info-new" class="hidden">
      <div class="form-check field-add">
        <div class="div-left">
          <%= radio_button_tag :address, "", true, id: "checked-new" %>
        </div>
        <div class="div-left" id="info-lable-new"></div>
      </div>
      <hr>
    </div>
    <%= label_tag :note, t("orders.note"), class: "form-lable" %>
    <%= text_area_tag :note, nil, placeholder: t("orders.note"), class: "form-control text-left px-3", id: "order_note" %>
    <div>
      <a href="#" class="button-new-address"><%= t("orders.add_new_address") %></a>
    </div>
  </div>
  <div class="row">
    <%= submit_tag t("orders.order").upcase, class: "btn btn-primary py-3 px-4 clear button-center" %>
  </div>
<% end %>
<!-- Form new address -->
<div id="form-new-info" class="hidden">
  <div class="col-md-8 mt-5 cart-wrap ftco-animate address-form form-new-address">
    <div class="cart-total mb-3">
        <div class="form-group">
          <%= label_tag :name_new, t("orders.fullname"), class: "form-lable" %>
          <%= text_field_tag :name_new, nil, placeholder: t("orders.fullname"), class: "form-control text-left px-3", id: "info-name" %>

          <%= label_tag :phone_new, t("orders.phone"), class: "form-lable" %>
          <%= phone_field_tag :phone_new, nil, placeholder: t("orders.phone"), class: "form-control text-left px-3", id: "info-phone" %>

          <%= label_tag :address_new, t("orders.address"), class: "form-lable" %>
          <%= text_field_tag :address_new, nil, placeholder: t("orders.address"), class: "form-control text-left px-3", id: "info-address" %>
        </div>
        <div class="row">
          <%= link_to t("orders.add_new").upcase,"#", class: "btn btn-primary py-3 px-4 button-center", id: "info-submit" %>
        </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag "custom", "data-turbolinks-track": "reload" %>

app/views/orders/_products_in_cart.html.erb
<table class="table">
  <thead class="thead-primary">
    <tr class="text-center">
      <th><%= t "images" %></th>
      <th><%= t "name" %></th>
      <th><%= t "price" %></th>
      <th><%= t "quantity" %></th>
      <th><%= t "total" %></th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |item| %>
      <tr>
        <td>
          <%= check_thumbnail? item%>
        </td>
        <td class="product-name">
          <%= item.name %>
        </td>
        <td class="product-price">
          <%= number_to_currency(item.price, locale: :vi) %>
        </td>
        <td class="product-name">
          <%= session[:cart]["#{item.id}"] %>
        </td>
        <td>
          <%= number_to_currency(item.price*session[:cart]["#{item.id}"], locale: :vi) %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3"></td>
      <td><%= t "orders.total_price" %></td>
      <td><%= number_to_currency(@total, locale: :vi) %></td>
    </tr>
  </tbody>
</table>

app/views/orders/index.html.erb
<%= stylesheet_link_tag :orders %>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div id="tracking">
        <div class="text-center tracking-status-intransit">
           <p class="tracking-status text-tight"><%= t "orders.history_orders" %></p>
        </div>
        <div class="tracking-list">
          <% if @orders.any? %>
            <%= render @orders %>
            <div class="pagination pagi-bottom justify-content-center">
              <%= paginate @orders %>
            </div>
          <% else %>
            <h1 class="text-center cart-index-title">
              <%= t "orders.no_order" %>
            </h1>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<section class="ftco-section ftco-cart">
  <div class="container">
    <div class="row">
      <div class="col-md-12 ftco-animate">
        <div class="cart-list">
          <%= render "products_in_cart" %>
        </div>
      </div>
    </div>

    <div class="row justify-content-end">
      <div class="col-md-8 mt-5 cart-wrap ftco-animate address-form">
        <div class="cart-total mb-3" style="padding: 40px;">
          <%= render "order_form" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body p-0">
          <div class="row pb-5 p-5">
            <table>
              <tr>
                <td class="col-md-3"><%= t "orders.fullname" %>:</td>
                <td class="col-md-6"><%= @order.name %></td>
              </tr>
              <tr>
                <td class="col-md-3"><%= t "orders.phone" %>:</td>
                <td class="col-md-6"><%= @order.phone %></td>
              </tr>
              <tr>
                <td class="col-md-3"><%= t "orders.address" %>:</td>
                <td class="col-md-6" rowspan="2"><%= @order.address %></td>
              </tr>
              <tr>
                <td class="col-md-3">&nbsp;</td>
              </tr>
              <tr>
                <td class="col-md-3"><%= t "orders.created_order" %>:</td>
                <td class="col-md-6"><%= l @order.created_at, format: :own %></td>
              </tr>
                <td class="col-md-3"><%= t "orders.status" %>:</td>
                <td class="col-md-6">
                  <span class="badge <%= t "class.#{@order.status}" %>">
                    <%= t("status_order.#{@order.status}") %>
                  </span>
                </td>
              </tr>
            </table>
            <div class="col-md-6 text-right">
              <% if can? :cancel, @order %>
                <%= link_to cancel_user_order_path(current_user, @order),
                    method: :put, data: { confirm: t("you_sure") } do
                %>
                  <button type="button" class="btn btn-danger btn-sm mb-4">
                    <i class="fa fa-times" aria-hidden="true"><%= t "orders.cancel" %></i>
                  </button>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="row p-5">
            <div class="col-md-12">
              <table class="table">
                <thead>
                  <tr>
                    <th class="border-0 text-uppercase small font-weight-bold"></th>
                    <th class="border-0 text-uppercase small font-weight-bold"><%= t "orders.product_name" %></th>
                    <th class="border-0 text-uppercase small font-weight-bold"><%= t "orders.quantity" %></th>
                    <th class="border-0 text-uppercase small font-weight-bold"><%= t "orders.price" %></th>
                    <th class="border-0 text-uppercase small font-weight-bold"><%= t "orders.total_price" %></th>
                  </tr>
                </thead>
                <tbody>
                  <%= render partial: "order_detail", collection: @order_details %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="d-flex flex-row-reverse bg-light text-dark p-4">
            <div class="py-3 px-5 text-right">
              <div class="mb-2"><%= t "orders.total" %></div>
              <div class="h2 font-weight-light"><%= number_to_currency(@total, locale: :vi) %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-5 mb-5"></div>
</div>