config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "orders#index"
      resources :orders do
        member do
          put :approve
          put :reject
        end
      end
      get "order_status/:status", to: "orders#index_by_status", as: :status
      resources :products, except: :delete do
        collection {post :import}
        member do
          delete :purge_images
          delete :purge_thumbnail
        end
      end
    end

    root "static_pages#home"
    get :home, to: "static_pages#home"
    get :menu, to: "products#index"
    get :about, to: "static_pages#about"
    get :blog, to: "static_pages#blog"
    get :contact, to: "static_pages#contact"
    get :order, to: "orders#new"
    get "/filter/:category_id", to: "products#filter", as: :filter

    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      delete "logout" => "devise/sessions#destroy"
    end
    resources :users, only: %i(show) do
      resources :orders, only: %i(index show) do
        put :cancel, on: :member
      end
    end
    resources :products, only: %i(index show)
    resources :orders, only: %i(new create)
    resources :carts
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  has_one_attached :thumbnail
  has_many_attached :images

  accepts_nested_attributes_for :category, allow_destroy: true,
                                           reject_if: :validate_nested

  scope :find_name, ->(name){where "name LIKE ?", "%#{name}%" if name.present?}
  scope :recent_products, ->{order created_at: :desc}
  scope :find_products_cart, ->(pr_id){where id: pr_id}
  scope :filter_category, (lambda do |category_id|
    where(category_id: category_id) if category_id.present?
  end)

  enum status: {disabled: 0, enabled: 1}

  delegate :name, to: :category, prefix: true

  validates :name, presence: true,
    length: {
      minimum: Settings.length.min_2,
      maximum: Settings.length.max_250
    }

  validates :price, presence: true,
                    numericality:
                    {
                      only_integer: false,
                      greater_than_or_equal_to: Settings.init_number
                    }

  validates :description, presence: true,
    length: {
      minimum: Settings.length.min_5,
      maximum: Settings.length.max_250
    }

  validates :quantity, presence: true,
                       numericality:
                       {
                         only_integer: true,
                         greater_than_or_equal_to: Settings.init_number
                       }

  validates :images,
            content_type:
            {
              in: Settings.image.format,
              message: I18n.t("validate_image.msg_format")
            },
            size:
            {
              less_than: Settings.image.size_1mb.megabytes,
              message: I18n.t("validate_image.msg_size")
            }

  def display_image input
    images[input].variant(resize: Settings.resize_images).processed
  end

  def display_thumbnail
    thumbnail.variant(resize: Settings.resize_thumbnail).processed
  end

  def self.handle_check spreadsheet, header, arr
    (Settings.row_2..spreadsheet.last_row).each do |i|
      row = [header, spreadsheet.row(i)].transpose.to_h
      begin
        check_create row, arr, i
      rescue ActiveRecord::RecordInvalid => e
        arr.push(I18n.t("validate_excel.row") + "#{i}  #{e.message}")
      end
      return arr if i == spreadsheet.last_row
    end
  end

  def validate_nested attribute
    return true if attribute[:name].blank?

    dem = 0
    Category.pluck(:name, :description).each do |item|
      next unless attribute[:name] == item[0] &&
                  attribute[:description] == item[1]

      dem = 1
      break
    end
    dem != 0
  end

  class << self
    private

    def check_create row, arr, index
      if check_status? row["status"]
        arr.push(index) unless Product.create! row
      else
        arr.push(I18n.t("validate_excel.row") + index.to_s +
                 I18n.t("validate_excel.check_status"))
      end
    end

    def check_status? status
      Product.statuses.include?(status) ||
        Product.statuses.values.include?(status)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminsController
  before_action :load_product,
                only: %i(show edit update purge_thumbnail destroy)
  before_action :load_order_details_with_product_id, only: :destroy

  def index
    @products = Product.recent_products
                       .page(params[:page])
                       .per(Settings.per_page_15)
  end

  def import
    arr_message = import_data params[:file]
    if arr_message.empty?
      flash[:success] = t "product_controller.msg_import_success"
    else
      flash[:info] = arr_message
    end
    redirect_to admin_products_url
  end

  def show; end

  def new
    @product = Product.new
    @product.build_category
  end

  def purge_thumbnail
    @product.thumbnail.purge
    redirect_back fallback_location: admin_product_path(@product)
  end

  def purge_images
    imge = ActiveStorage::Attachment.find_by id: params[:id]
    imge.purge
    redirect_back fallback_location: admin_root_path
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:success] = t "update_product.msg_update_success"
      redirect_to admin_product_path(@product)
    else
      flash[:danger] = t "update_product.msg_update_fail"
      render :edit
    end
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:info] = t "product_controller.msg_create_success"
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def destroy
    if @order_details.present?
      check_status
    else
      @product.destroy
      flash[:success] = t "product_controller.msg_delete_success"
    end
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product)
          .permit(:thumbnail, :name, :price, :description, :quantity,
                  :status, :category_id, images: [],
                  category_attributes: [:name, :description])
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "product_controller.msg_show_failer"
    redirect_to admin_products_path
  end

  def load_order_details_with_product_id
    @order_details = OrderDetail.where(product_id: @product)
  end

  def check_status
    if @product.enabled?
      @product.disabled!
      flash[:success] = t "product_controller.msg_delete_change"
    else
      flash[:danger] = t "product_controller.msg_no_delete"
    end
  end

  def import_data file
    arr = []
    spreadsheet = Roo::Spreadsheet.open file
  rescue StandardError
    arr.push(I18n.t("validate_excel.format"))
    arr
  else
    header = spreadsheet.row(Settings.row_1)
    if (header - Product.column_names).any?
      arr.push(I18n.t("validate_excel.model_fail"))
      return arr
    else
      Product.handle_check spreadsheet, header, arr
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show
  before_action :categories_select_id_name, only: %i(index filter)
  authorize_resource

  def index
    @products = @q.result.enabled

    if @products.empty?
      @products = Product
      flash.now[:danger] = t "menu_page.search_pro_nil"
    end

    @products = @products.recent_products
                         .page(params[:page])
                         .per(Settings.per_page_16)
    render "static_pages/menu"
  end

  def new; end

  def create; end

  def show; end

  def filter
    @products = Product.enabled
                       .filter_category(params[:category_id])
                       .page(params[:page])
                       .per(Settings.per_page_16)
    flash.now[:danger] = t "menu_page.filter_category_nil" if @products.empty?
    render "static_pages/menu"
  end

  private

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product

    flash[:danger] = t "show_product_fail"
    redirect_to root_url
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def gravatar_for product, options = {size: Settings.gravatar.size_80}
    gravatar_id = Digest::MD5.hexdigest(product.name.downcase)
    size = options[:size]
    gravatar_url =
      "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: product.name, class: "gravatar")
  end

  def check_image?
    @product.thumbnail.attached?
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def gravatar_for product, options = {size: Settings.length.max_250}
    gravatar_id = Digest::MD5.hexdigest(product.name.downcase)
    size = options[:size]
    gravatar_url =
      "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: product.name, class: "gravatar")
  end

  def check_sold_out? quantity
    quantity.zero?
  end

  def check_thumb? thumbnail
    thumbnail.attached?
  end
end

app/views/admin/products/_category_field.html.erb
<fieldset>
  <%= cate.label :name , t("page_category_field_admin.name")%>
  <%= cate.text_field :name %>
  <%= cate.label :description, t("page_category_field_admin.description")%>
  <%= cate.text_field :description %>
  <%= cate.hidden_field :_destroy %>
  <%= link_to t("page_category_field_admin.remove"), "#", class: "remove-fields" %>
</fieldset>

app/views/admin/products/_form.html.erb
<h4 class="lable-form-index"><%= t "page_new_product_admin.excel" %></h4>
<%= form_tag import_admin_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag t("page_new_product_admin.import"), class: "btn btn-success" %>
<% end %>
<h4><%= t "page_new_product_admin.or" %></h4>
<button class="btn-show-hide"><%= t "page_new_product_admin.enter_manually" %></button>
<div class="form-new">
  <%= form_for [:admin, @product] do |f| %>
    <div class="lable-form-index">
      <%= f.label :thumbnail, t("page_create_product_admin.thumbnail") %><br>
    </div>
    <%= f.file_field :thumbnail %>
    <div class="lable-form-index">
      <%= f.label :name, t("page_create_product_admin.name") %>
      <%= f.text_field :name, class: "form-control" %>
      <%= show_message_for_field(@product, :name) %>
    </div>
    <div class="lable-form-index">
      <%= f.label :price, t("page_create_product_admin.price") %>
      <%= f.text_field :price, class: "form-control" %>
      <%= show_message_for_field(@product, :price) %>
    </div>
    <div class="lable-form-index">
      <%= f.label :description, t("page_create_product_admin.description") %>
      <%= f.text_field :description, class: "form-control" %>
      <%= show_message_for_field(@product, :description) %>
    </div>
    <div class="lable-form-index">
      <%= f.label :quantity, t("page_create_product_admin.quantity") %>
      <%= f.text_field :quantity, class: "form-control" %>
      <%= show_message_for_field(@product, :quantity) %>
    </div>
    <div class="lable-form-index">
      <%= f.label :status, t("page_create_product_admin.status") %>
      <%= f.select :status, Product.statuses.keys %>
    </div>
    <div class="lable-form-index">
      <%= f.label :category_id, t("page_create_product_admin.category") %>
      <%= f.collection_select :category_id, Category.all, :id, :name,
        class: "form-control" %><br>
      <%= f.fields_for :category do |cate| %>
      <% end %>
    </div>
    <%= link_to_add_fields t("page_create_product_admin.add_category"), f, :category%><br>
    <div class="lable-form-index">
      <%= f.label :images, t("page_create_product_admin.images") %>
    </div>
    <%= f.file_field :images, multiple: true %>
    <div class="submit-form-index">
      <%= f.submit t("page_create_product_admin.submit"),
          class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag :custom %>

app/views/admin/products/_product.html.erb
<% if @products.any? %>
  <% @products.each do |product| %>
    <div class="card card-inside">
      <% if product.thumbnail.present? %>
        <%= link_to image_tag(product.display_thumbnail, class: "style_image"), admin_product_path(product) %><br>
      <% else %>
        <%= link_to (gravatar_for product, size: Settings.gravatar.size_198,
            class: "style_image"), admin_product_path(product) %><br>
      <% end %>
      <div class="card-text card-margin">
        <%= link_to product.name, admin_product_path(product), class: "style_link" %>
        <p class="card-p"><%= t "page_index_product_admin.price" %><%= link_to product.price, "#", class: "card-p" %></p>
        <p class="card-p"><%= t "page_index_product_admin.quantity" %><%= link_to product.quantity, "#", class: "card-p" %></p>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="index_product_nil">
    <h1><%= t "page_index_product_admin.notification_nil" %></h1>
    <%= link_to t("page_index_product_admin.button"), new_admin_product_path,
      class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/products/_update_product.html.erb
<%= form_for [:admin, @product] do |f| %>
  <div class="lable-form-index" >
    <%= f.label :thumbnail, t("page_create_product_admin.thumbnail") %><br>
  </div>
  <div>
    <% if check_image? %>
      <%= image_tag @product.display_thumbnail %>
      <%= link_to t("delete"),
          purge_thumbnail_admin_product_path(@product),
          method: :delete, data: {confirm: t("confirm")},
          class: "btn btn-success form-update-delete" %>
    <% else %>
      <%= gravatar_for @product, size: Settings.size_80 %>
    <% end %>
  </div>
  <%= f.file_field :thumbnail %>
  <div class="lable-form-index">
    <%= f.label :name, t("page_create_product_admin.name") %>
    <%= f.text_field :name, class: "form-control" %>
    <%= show_message_for_field(@product, :name) %>
  </div>
  <div class="lable-form-index">
    <%= f.label :price, t("page_create_product_admin.price") %>
    <%= f.text_field :price, class: "form-control" %>
    <%= show_message_for_field(@product, :price) %>
  </div>
  <div class="lable-form-index">
    <%= f.label :description, t("page_create_product_admin.description") %>
    <%= f.text_field :description, class: "form-control" %>
    <%= show_message_for_field(@product, :description) %>
  </div>
  <div class="lable-form-index">
    <%= f.label :quantity, t("page_create_product_admin.quantity") %>
    <%= f.text_field :quantity, class: "form-control" %>
    <%= show_message_for_field(@product, :quantity) %>
  </div>
  <div class="lable-form-index">
    <%= f.label :status, t("page_create_product_admin.status") %>
    <%= f.select :status, Product.statuses.keys %>
  </div>
  <div class="lable-form-index">
    <%= f.label :category_id, t("page_create_product_admin.category") %>
    <%= f.collection_select :category_id, Category.all, :id, :name,
      class: "form-control" %><br>
    <%= f.fields_for :category do |cate| %>
    <% end %>
    <%= link_to_add_fields t("page_create_product_admin.add_category"), f, :category %><br>
  </div>
  <div class="lable-form-index">
    <%= f.label :images, t("page_create_product_admin.images") %>
    <% if @product.images.attached? %>
      <% @product.images.each do |img| %>
        <div class="images-update">
          <%= image_tag img.variant(resize_to_limit: [300,300]) %>
          <%= link_to t("delete"), purge_images_admin_product_path(img),
              method: :delete, data: {confirm: t("confirm")},
              class: "btn btn-success form-update-delete" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.file_field :images, multiple: true %>
  <div class="submit-form-index">
    <%= f.submit t("page_create_product_admin.submit"),
        class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<% provide :title, t("update_product.title") %>
<h1 class="subject">
  <%= t "update_product.title" %>
</h1>
<%= render "update_product" %>

app/views/admin/products/index.html.erb
<% provide :title, t("page_index_product_admin.title") %>
<h1 class="subject">
  <%= t "page_index_product_admin.subject" %>
</h1>
<%= paginate @products %>
<div class="container_index">
  <%= render "product" %>
</div>
<%= paginate @products %>

app/views/admin/products/new.html.erb
<% provide :title, (t"page_create_product_admin.title") %>
<h1 class="subject">
  <%= t "page_create_product_admin.title" %>
</h1>
<%= render "form" %>

app/views/admin/products/show.html.erb
<% provide :title, @product.name %>
<h1 class="title-show">
  <%= t "page_show_product_admin.title" %>
</h1>
<table class="table table-bordered">
  <thead>
    <tr class="tr-head-show">
      <th class="th-head-show" >
        <%= t "page_show_product_admin.table.img" %>
      </th>
      <th class="th-head-show" >
        <%= t "page_show_product_admin.table.name" %>
      </th>
      <th class="th-head-show">
        <%= t "page_show_product_admin.table.price" %>
      </th>
      <th class="th-head-show-width40" >
        <%= t "page_show_product_admin.table.description" %>
      </th>
      <th class="th-head-show" >
        <%= t "page_show_product_admin.table.quantity" %>
      </th>
      <th class="th-head-show">
        <%= t "page_show_product_admin.table.status" %>
      </th>
      <th class="th-head-show">
        <%= t "page_show_product_admin.table.category" %>
      </th>
      <th colspan="2" class="th-action"><%= t "page_show_product_admin.table.action" %></th>
    </tr>
  </thead>
  <tbody>
    <tr class="tr-body-show">
      <td class="td-body-show">
        <% if check_image? %>
          <%= image_tag @product.display_thumbnail %>
        <% else %>
          <%= gravatar_for @product, size: Settings.size_80 %>
        <% end %>
      </td>
      <td class="td-name-body-show"><%= @product.name %></td>
      <td class="td-body-show"><%= @product.price %></td>
      <td class="td-body-show"><%= @product.description %></td>
      <td class="td-body-show"><%= @product.quantity %></td>
      <td class="td-body-show"><%= @product.status %></td>
      <td class="td-body-show"><%= @product.category_name %></td>
      <td>
        <%= link_to t("page_show_product_admin.edit"), edit_admin_product_path(@product),
          class: "btn btn-success td-action-body-show" %>
      </td>
      <td>
        <%= button_to t("page_show_product_admin.delete"), admin_product_path(@product),
          method: :delete, data: {confirm: t("confirm")},
          class: "btn btn-danger td-action-body-show" %>
      </td>
    </tr>
  </tbody>
</table>
<h4><%= t "page_show_product_admin.images" %></h4>
<div class="container-images-show">
  <% (0...@product.images.count).each do |img| %>
    <div class="image-show">
      <%= image_tag (@product.display_image(img)) if @product.images.attached? %>
    </div>
  <% end %>
</div>