config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "orders#index"
      resources :orders do
        member do
          put :approve
          put :reject
        end
      end
      get "order_status/:status", to: "orders#index_by_status", as: :status
      resources :products, except: :delete do
        collection {post :import}
        member do
          delete :purge_images
          delete :purge_thumbnail
        end
      end
    end

    root "static_pages#home"
    get :home, to: "static_pages#home"
    get :menu, to: "products#index"
    get :about, to: "static_pages#about"
    get :blog, to: "static_pages#blog"
    get :contact, to: "static_pages#contact"
    get :order, to: "orders#new"
    get "/filter/:category_id", to: "products#filter", as: :filter

    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      delete "logout" => "devise/sessions#destroy"
    end
    resources :users, only: %i(show) do
      resources :orders, only: %i(index show) do
        put :cancel, on: :member
      end
    end
    resources :products, only: %i(index show)
    resources :orders, only: %i(new create)
    resources :carts
  end
end

app/views/layouts/_footer.html.erb
<footer class="ftco-footer ftco-section">
  <div class="container">
    <div class="row">
      <div class="mouse">
        <a href="#" class="mouse-icon">
          <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
        </a>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">
            <%= t("food_drink") %>
          </h2>
          <p>
            <%= t("footer.introduce") %>
          </p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-5">
          <h2 class="ftco-heading-2"><%= t("menu") %></h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block"><%= t("about") %></a></li>
            <li><a href="#" class="py-2 d-block"><%= t("blog") %></a></li>
            <li><a href="#" class="py-2 d-block"><%= t("contact") %></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2"><%= t("help") %></h2>
          <div class="d-flex">
            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
              <li>
                <a href="#" class="py-2 d-block"><%= t("footer.shipping_information") %></a>
              </li>
              <li>
                <a href="#" class="py-2 d-block"><%= t("footer.returns_and_exchanges") %></a>
              </li>
              <li>
                <a href="#" class="py-2 d-block"><%= t("footer.terms_and_conditions") %></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2"><%= t("footer.contact_info") %></h2>
          <div class="block-23 mb-3">
            <ul>
              <li>
                <span class="icon icon-map-marker"></span>
                <span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
              </li>
              <li>
                <a href="#">
                  <span class="icon icon-phone"></span>
                  <span class="text">+2 392 3929 210</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="icon icon-envelope"></span>
                  <span class="text">info@yourdomain.com</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          <%= t("footer.copyright") %> &copy;
          <script>document.write(new Date().getFullYear());</script>
          <%= t("footer.template_made_by") %>
          <a href="https://colorlib.com" target="_blank">
            <%= t("food_drink") %>
          </a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.text_field :name, class: "text", placeholder: t("form.full_name") %>
  <%= show_message_for_field(@user, :name) %>
  <%= f.email_field :email, class: "text", placeholder: t("form.email") %>
  <%= show_message_for_field(@user, :email) %>
  <%= f.password_field :password, class: "password", placeholder: t("form.password") %>
  <%= show_message_for_field(@user, :password) %>
  <%= f.password_field :password_confirmation, class: "password", placeholder: t("form.password_confirmation") %>
  <%= show_message_for_field(@user, :password_confirmation) %>
  <%= f.submit t("sign_up.sign_up").upcase, class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<!-- START header -->
<div class="py-1 bg-primary">
  <div class="container">
    <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
      <div class="col-lg-12 d-block">
        <div class="row d-flex">
          <div class="col-3 pr-2 d-flex topper align-items-center">
            <div class="icon mr-2 d-flex justify-content-center align-items-center">
              <span class="icon-phone2"></span>
            </div>
            <span class="text">+ 1235 2355 98</span>
          </div>
          <div class="col-7 pr-8 d-flex topper align-items-center d-flex flex-row-reverse">
           <%= render "shared/filter_products_by_name" %>
          </div>
          <div class="col-2 pr-2 d-flex topper align-items-center text-lg-right">
            <span class="text">
              <ul class="icon-inline">
                <li>
                  <%= link_to locale: :vi do %>
                    <%= image_tag "/assets/images/icons-vi.png", class: "icons-lang" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to locale: :en do %>
                    <%= image_tag "/assets/images/icons-en.png", class: "icons-lang" %>
                  <% end %>
                </li>
              </ul>
             </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <%= link_to t("food_drink"), root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to t("home"), root_path, class: "nav-link" %>
        </li>
        <li class="nav-item"><%= link_to t("menu"), menu_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to t("about"), about_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to t("blog"), blog_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to t("contact"), contact_path, class: "nav-link" %></li>
        <li class="nav-item cta cta-colored">
          <%= link_to carts_path,
              class: "nav-link" do %>
            <span class="icon-shopping_cart"></span>
            <%= [@carts.count] if @carts.present? %>
          <% end %>
        </li>
        <li class="nav-icon dropdown">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
            <img src="/assets/images/avatar-default.png" class="avatar-default">
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to t("profile"), user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to t("setting"), edit_user_registration_path, class: "dropdown-item" %></li>
              <% if current_user.role? %>
                <li>
                  <%= link_to t("dashboard"), admin_root_path, class: "dropdown-item" %>
                </li>
              <% end %>
              <li>
                <%= link_to t("orders.history_orders"), user_orders_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                <%= button_to t("log_out"), logout_path, method: :delete, class: "dropdown-item" %>
              </li>
            <% else %>
              <li><%= link_to t("sign_up.sign_up"), signup_path, class: "dropdown-item" %></li>
              <li><%= link_to t("log_in.log_in"), login_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- END header -->

app/views/layouts/_header_admin.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title nav_title_cus">
      <%= link_to t("food_drink"), admin_root_path, class: "site_title"  %>
    </div>
    <div class="clearfix"></div>
    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <%= image_tag("avatar.png", class: "img-circle profile_img") %>
      </div>
      <div class="profile_info">
        <span><%= t "welcome" %>,</span>
        <h2><%= show_name %></h2>
      </div>
    </div>
    <!-- /menu profile quick info -->
    <br/>
    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3><%= t "manager_orders" %></h3>
        <ul class="nav side-menu">
          <li>
            <a>
              <i class="fa fa-list-alt"></i>
              <%= t "manager_orders" %>
              <span class="fa fa-chevron-down" aria-hidden="true"></span>
            </a>
            <ul class="nav child_menu">
              <li><%= link_to t("orders.all"), admin_orders_path %></li>
              <li><%= link_to t("status_order.open"), admin_status_path(status: :open) %></li>
              <li><%= link_to t("status_order.confirmed"), admin_status_path(status: :confirmed) %></li>
              <li><%= link_to t("status_order.shipping"), admin_status_path(status: :shipping) %></li>
              <li><%= link_to t("status_order.completed"), admin_status_path(status: :completed) %></li>
              <li><%= link_to t("status_order.cancelled"), admin_status_path(status: :cancelled) %></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="menu_section">
        <h3><%= t "manager_products" %></h3>
        <ul class="nav side-menu">
          <li>
            <a>
              <i class="fa fa-product-hunt" aria-hidden="true"></i>
              <%= t "product.products" %>
              <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
              <li><%= link_to t("product.all_products"), admin_products_path %></li>
              <li><%= link_to t("product.categories"), "#" %></li>
              <li><%= link_to t("product.add_product"), new_admin_product_path %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav side-menu">
          <li>
            <a>
              <i class="fa fa-bar-chart" aria-hidden="true"></i>
              <%= t "manager_analytic" %>
              <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
              <li><%= link_to t("analytic_week"), "#" %></li>
              <li><%= link_to t("analytic_month"), "#" %></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="menu_section">
        <h3><%= t "manager_accounts" %></h3>
        <ul class="nav side-menu">
          <li>
            <a>
              <i class="fa fa-users" aria-hidden="true"></i>
              <%= t "account.accounts" %>
              <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
              <li><%= link_to t("account.accounts"), "#" %></li>
              <li><%= link_to t("account.blocked"), "#" %></li>
            </ul>
          </li>
          <li>
            <%= link_to root_path do %>
              <i class="fa fa-home" aria-hidden="true"></i><%= t "back_home" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <!-- /sidebar menu -->
  </div>
</div>
<div class="top_nav">
  <div class="nav_menu">
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>
    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right style-language">
      <span class="text">
        <ul style="list-style-type: none; ">
          <li>
            <%= link_to locale: :vi do %>
              <%= image_tag "/assets/images/icons-vi.png", class: "icons-lang" %>
            <% end %>
          </li>
          <li>
            <%= link_to locale: :en do %>
              <%= image_tag "/assets/images/icons-en.png", class: "icons-lang" %>
            <% end %>
          </li>
        </ul>
      </span>
    </div>
    <nav class="nav navbar-nav">
      <ul class=" navbar-right">
        <li class="nav-item dropdown open dropdown_right">
          <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag "avatar.png" %>
          </a>
          <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item"  href="javascript:;">
              <span class="badge bg-red pull-right"></span>
              <span><%= show_name %></span>
            </a>
            <%= link_to(raw("<i class='fa fa-sign-out pull-right'></i>")<< t("logout"), "#", {class: "dropdown-item"}) %>
          </div>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title yield :title %></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/assets/admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/admin/fonts/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/admin/css/custom.min.css" rel="stylesheet">
    <link href="/assets/admin/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/assets/admin/css/toastr.css" rel="stylesheet"/>
    <link href="/assets/admin/css/custom.css" rel="stylesheet"/>
    <%= stylesheet_link_tag :admin %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body class="nav-md" >
    <div class="container body">
      <div class="main_container">
          <%= render "layouts/header_admin" %>
          <div class="right_col" role="main">
              <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
              <% end %>
              <%= yield %>
          </div>
        </div>
      </div>
    <%= javascript_pack_tag :application %>
    <script src="/assets/admin/js/jquery.min.js"></script>
    <script src="/assets/admin/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/admin/js/custom.min.js"></script>
    <script src="/assets/admin/js/jquery.dataTables.min.js"></script>
    <script src="/assets/admin/js/dataTables.bootstrap.min.js"></script>
    <script src="/assets/admin/js/toastr.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/animate.css">
    <link rel="stylesheet" href="/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="/assets/css/aos.css">
    <link rel="stylesheet" href="/assets/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/assets/css/jquery.timepicker.css">
    <link rel="stylesheet" href="/assets/css/flaticon.css">
    <link rel="stylesheet" href="/assets/css/icomoon.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container flash-noti">
      <% flash.each do |message_type, message| %>
        <% if message_type == "notice" %>
          <div class="alert alert-success"><%= message %></div>
        <% elsif message_type == "alert" %>
          <div class="alert alert-danger"><%= message %></div>
        <% else %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <% end %>
    </div>
    <%= yield %>

    <%= render "layouts/footer" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.easing.1.3.js"></script>
    <script src="/assets/js/jquery.waypoints.min.js"></script>
    <script src="/assets/js/jquery.stellar.min.js"></script>
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="/assets/js/aos.js"></script>
    <script src="/assets/js/jquery.animateNumber.min.js"></script>
    <script src="/assets/js/bootstrap-datepicker.js"></script>
    <script src="/assets/js/scrollax.min.js"></script>
    <script src="/assets/js/main.js"></script>
  </body>
</html>

app/views/layouts/signup_signin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "signup_signin", media: "all", "data-turbolinks-track": true %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>